import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.lineicons.com/5.0/lineicons.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
